#!/usr/bin/env bash
# Refuse to commit secret material.
#
# Why this exists: the onstart script generated by vast_run.sh embeds the TabPFN license
# token verbatim. It used to be written inside the repository, an aborted run left four of
# them behind, and a directory-wide `git add` swept them into a commit that was pushed to
# the shared remote -- putting a live token into history, where deleting the file does not
# remove it. The scanner is the backstop for that class of mistake: a generated file, a
# pasted key, an exported variable, in a file nobody meant to commit.
#
# Usage:
#   check_no_secrets.sh                # scan staged content (pre-commit use)
#   check_no_secrets.sh <path> [...]   # scan specific files or directories
#
# Exit 0 clean, 1 if anything matched. Matching VALUES ARE NEVER PRINTED -- only the file,
# the line and which pattern matched, because printing a secret into a terminal or a CI log
# is the same leak again in a different medium.
set -uo pipefail

PATTERNS=(
    'tabpfn_sk_[A-Za-z0-9_-]{20,}|TabPFN license token'
    'hf_[A-Za-z0-9]{25,}|HuggingFace token'
    'ghp_[A-Za-z0-9]{30,}|GitHub personal access token'
    'github_pat_[A-Za-z0-9_]{50,}|GitHub fine-grained token'
    'sk-[A-Za-z0-9]{32,}|OpenAI-style key'
    'AKIA[0-9A-Z]{16}|AWS access key id'
    '-----BEGIN [A-Z ]*PRIVATE KEY-----|private key'
    '(VAST_API_KEY|TABPFN_TOKEN|HF_TOKEN|GITHUB_TOKEN)[[:space:]]*=[[:space:]]*['"'"'"]?[A-Za-z0-9_-]{20,}|exported credential'
)

if [ "$#" -gt 0 ]; then
    files="$(for a in "$@"; do [ -f "$a" ] && printf '%s\n' "$a"; [ -d "$a" ] && find "$a" -type f ! -path '*/.git/*'; done)"
else
    # Staged content only: the question is what is about to be committed, not what exists.
    # A directory-wide `git add` staged files nobody intended to include; scanning the
    # intended directory instead would have missed exactly that.
    files="$(git diff --cached --name-only --diff-filter=ACM)"
fi

[ -z "$files" ] && exit 0

hits=0
while IFS= read -r f; do
    [ -z "$f" ] && continue
    [ -f "$f" ] || continue
    case "$f" in
        *.png|*.jpg|*.jpeg|*.gif|*.pdf|*.parquet|*.npy|*.ckpt|*.zip|*.gz) continue ;;
    esac
    for spec in "${PATTERNS[@]}"; do
        pat="${spec%%|*}"
        label="${spec##*|}"
        # -I skips binaries; -n gives the line number; the value itself is never echoed.
        if grep -qInE -- "$pat" "$f" 2>/dev/null; then
            echo "BLOCKED: possible secret ($label) in $f" >&2
            grep -InE -- "$pat" "$f" 2>/dev/null | cut -d: -f1 | head -3 \
                | while read -r ln; do echo "         line $ln" >&2; done
            hits=$((hits + 1))
        fi
    done
done <<< "$files"

if [ "$hits" -gt 0 ]; then
    echo "" >&2
    echo "Commit refused: $hits file(s) match a secret pattern." >&2
    echo "If this is a false positive, use:  git commit --no-verify" >&2
    echo "If it is real: remove it, and ROTATE the credential -- it is already exposed." >&2
    exit 1
fi
exit 0
